#!/usr/bin/env python3
import subprocess
import gbconfig
import logging
from resources import testResult
from tests.unit_test import register_test

'''
    Each unit test should consist of a class which contains a run method. 
    Gradebot will automatically load all unit tests found in the correct test
    folder and each test will register themselves with gradebot by calling
    register_test which is found at the bottom of the file.

    The run method should expect both a submission and config object which 
    it can use to set up and run the required test. This will contain information 
    such as the path to the file/s to test. It then must return a result object which 
    contains the status of the test, how many points to award for the test,
    and any autogenerated comments you would like to insert.
'''
class ut1:
    def __init__(self, config):
        self.name = "ut1"
        self.maxPoints = 10
        self.config = config

    # Define your unit test here
    def run(self, submission):
        r = testResult.ut_result()
        logging.info("Running unit test 1....")
        r.name = self.name
        r.maxPoints = self.maxPoints

        r.passed = True
        r.points = self.maxPoints
        r.comments = "Automated comments can go here"

        return r 

if __name__ == "__main__":
    print("hello")

# Register this unit test with gradebot
register_test("ut1",ut1)
